### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by qiminchen** [hjwdzh/FrameNet#4]
Hi Jingwei, I was trying to compile the render but ended up the error below all the time. Do you have any ideas on how I can solve this? Should I change `OPENCV_INCLUDE_DIR` and `OPENCV_LIBRARY_DIR`? Any suggestions would be very appreciated.
```
Traceback (most recent call last):
  File "visualize_field.py", line 4, in <module>
    import Render.render as render
  File "/home/qimin/Projects/Cameralocalization/src/Render/render.py", line 4, in <module>
    Render = cdll.LoadLibrary('./Render/libRender.so')
  File "/home/qimin/anaconda3/envs/framenet/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/qimin/anaconda3/envs/framenet/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./Render/libRender.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE
```
Here is the output of `pkg-config --libs opencv`
```
-L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_freetype -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
```
and `pkg-config --cflags opencv`
```
-I/usr/local/include/opencv -I/usr/local/include
```

So I modified the `compile.sh`
```
export PATH=$PATH:/usr/local/cuda-10.1/bin
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64

export OPENCV_INCLUDE_DIR=/usr/local/include
export OPENCV_LIBRARY_DIR=/usr/local/lib

export CFLAGS="-I/usr/local/include/opencv -I$OPENCV_INCLUDE_DIR"
export DFLAGS="-L$OPENCV_LIBRARY_DIR -lopencv_core -lopencv_highgui"

g++ -std=c++11 -c main.cpp $CFLAGS -O2 -o main.o -fPIC
g++ -std=c++11 main.o $CFLAGS $DFLAGS -O2 -o libRender.so -shared -fPIC

#g++ -std=c++11 main.o buffer.o loader.o render.o $CFLAGS $DFLAGS -o render -lcudart

#rm *.o
```

**Comment by hjwdzh** [comment]
It is due to different version of opencv. You will need to link an additional library via -lopencv_imgcodecs.
